POST http://localhost:8080/api/v1/users/register
Content-Type: application/json

{
  "username": "james",
  "role": "user",
  "email": "kinuthiajohn@gmail.com",
  "password": "Lightyagami"
}

###
GET http://localhost:8080/api/v1/users/all

###
GET http://localhost:8080/api/v1/users/2/get

###
DELETE http://localhost:8080/api/v1/users/2/delete

###
DELETE http://localhost:8080/api/v1/users/delete/all